### PR TITLE
Calculation of Imperfect Spoiling Correction Parameters

### PR DESCRIPTION
**Pull request by mfcallaghan**
New module in toolbox to calculate transmit field dependent coefficients that correct T1 estimation for the effects of imperfect spoiling.

Input:
Full details of protocol settings (TRs, flip flip angles, spoiling conditions) and expected ranges for B1+ and T1 times.  T2 and diffusion coefficient also required.

Output:
JSON file in specified directory containing the coefficients and a structure that can be copied to a hmri_local_defaults file.

### CODE REVIEW

**Comment by ktabelow** [comment]
I generated an error with the default settings

Failed  'Imperfect Spoiling Calc.'
Error using  .* 
Matrix dimensions must agree.
In file "/Users/tabelow/Programs/spm12/toolbox/hmriTbx-FIL/hmri_corr_imperf_spoil.m" (???), function "hmri_corr_imperf_spoil" at line 113.

The following modules did not run:
Failed: Imperfect Spoiling Calc.

**Comment by mfcallaghan** [comment]
Incompatible with Matlab R2016 and earlier.  Fixed and will be committed as separate PR.

**Comment by ktabelow** [comment]
With [1bc8b87](https://github.com/hMRI-group/hMRI-toolbox/pull/10/commits/1bc8b87097c5cecd50f05ac300292378bf8e3778) I was able to run it. 

Further comment: Are there any physical limits for the simulation parameters? I tried really nonsense value, the code still calculated something, but is it useful? The tbx config has some range tests for the user input, but is it sufficient?

**Comment by mfcallaghan** [comment]
In practice one probably could define a range but we have left it flexible since in theory they could vary a lot (field strength, in vivo / ex vivo, etc.).  I would expect users of this module to have good understanding of what the ranges are.  However, if the consensus is that defined limits would be better we are happy to add this.

**Comment by ktabelow** [comment]
I just want to ensure the module does not crash! 
If there are not obvious physical limits, it is probably not necessary to limit the parameters.
However, I was able to crash it using a negative spoiler gradient duration. Just these kind of insane user input.

**Pull request closed without merging**
