### PR TITLE
Save GM, WM and CSF PD segmentations for quality control

### PR DESCRIPTION
**Pull request by SherS2**

### CODE REVIEW

**Comment by lukeje** [comment]
Hey Siya, I tried to make the title more descriptive; please feel free to alter it if I got something wrong.

**Comment by SherS2** [comment]
This is not the correct branch

**Comment by SherS2** [comment]
https://github.com/SherS2/hMRI-toolbox/tree/ss_devHiRes

**Comment by lukeje** [comment]
@SherS2 I think I can't change the source branch. If you can't change it either (with the edit button at the top of the page), then you will need to make a new pull request with the correct branch.

**Pull request closed without merging**
